using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Seeing.Agent.Acp.Backends;
using Seeing.Agent.Configuration;
using Seeing.Agent.Core.Interfaces;
using Seeing.Agent.Core.Models;
using Seeing.Agent.Core.Permission;

namespace Seeing.Agent.Acp.Hosting;

/// <summary>
/// 根据 <see cref="SeeingAgentOptions.Acp"/> 后端配置动态注册 Passthrough Agent。
/// </summary>
public static class AcpDynamicAgentRegistrar
{
    public const string AgentNamePrefix = "acp-";
    public const string AutoTag = "acp-auto";

    public static string GetAgentName(string backendId) => AgentNamePrefix + backendId;

    public static async Task RegisterAsync(
        IAgentRegistry agentRegistry,
        IAcpBackendRegistry backendRegistry,
        IOptions<SeeingAgentOptions> options,
        ILogger logger,
        CancellationToken cancellationToken = default)
    {
        if (!options.Value.Acp.Enabled)
        {
            logger.LogDebug("ACP disabled, skipping dynamic agent registration");
            return;
        }

        var backends = backendRegistry.GetEnabledBackends();
        if (backends.Count == 0)
        {
            logger.LogWarning("ACP enabled but no backends configured, no passthrough agents registered");
            return;
        }

        var enabledBackendIds = backends.Select(b => b.Id).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var existingAgents = await agentRegistry.GetAgentsAsync().ConfigureAwait(false);

        foreach (var backend in backends)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var agentName = GetAgentName(backend.Id);
            if (agentRegistry.HasAgent(agentName))
            {
                logger.LogDebug("ACP agent {AgentName} already exists, skipping auto-registration", agentName);
                continue;
            }

            if (existingAgents.Any(a =>
                    a.Runtime == AgentRuntime.AcpPassthrough &&
                    string.Equals(a.AcpBackend, backend.Id, StringComparison.OrdinalIgnoreCase)))
            {
                logger.LogDebug(
                    "ACP backend {BackendId} already mapped to a passthrough agent, skipping {AgentName}",
                    backend.Id,
                    agentName);
                continue;
            }

            var agent = CreateAgentInfo(backend);
            await agentRegistry.RegisterAgentAsync(agent).ConfigureAwait(false);
            logger.LogInformation(
                "Registered ACP passthrough agent {AgentName} for backend {BackendId} ({Command})",
                agentName,
                backend.Id,
                backend.Command);
        }

        foreach (var stale in existingAgents.Where(IsAutoGeneratedPassthroughAgent))
        {
            if (string.IsNullOrWhiteSpace(stale.AcpBackend) ||
                enabledBackendIds.Contains(stale.AcpBackend))
                continue;

            if (agentRegistry.UnregisterAgent(stale.Name))
            {
                logger.LogInformation(
                    "Unregistered stale ACP passthrough agent {AgentName} (backend {BackendId} removed)",
                    stale.Name,
                    stale.AcpBackend);
            }
        }
    }

    public static AgentInfo CreateAgentInfo(AcpBackendDescriptor backend)
    {
        var commandName = Path.GetFileName(backend.Command);
        return new AgentInfo
        {
            Name = GetAgentName(backend.Id),
            Description = $"ACP 透传 · {backend.Id} ({commandName})",
            Mode = AgentMode.Primary,
            Runtime = AgentRuntime.AcpPassthrough,
            AcpBackend = backend.Id,
            IsNative = false,
            Category = "acp",
            Tags = new List<string> { "acp", AutoTag, backend.Id },
            DeniedTools = new List<string> { "task" },
            PermissionRules = new List<PermissionRuleEntry>
            {
                PermissionRuleEntry.Deny(PermissionKind.Tool, "task", 0, "acp-passthrough")
            }
        };
    }

    private static bool IsAutoGeneratedPassthroughAgent(AgentInfo agent) =>
        agent.Runtime == AgentRuntime.AcpPassthrough &&
        agent.Tags.Contains(AutoTag, StringComparer.OrdinalIgnoreCase);
}
