-- Quartz.NET SQLite 表结构（Microsoft.Data.Sqlite）
-- 官方脚本：https://github.com/quartznet/quartznet/blob/main/database/tables/tables_sqlite.sql

-- 清理已存在的表（仅在需要重新初始化时使用）
-- DROP TABLE IF EXISTS QRTZ_FIRED_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_PAUSED_TRIGGER_GRPS;
-- DROP TABLE IF EXISTS QRTZ_SCHEDULER_STATE;
-- DROP TABLE IF EXISTS QRTZ_LOCKS;
-- DROP TABLE IF EXISTS QRTZ_SIMPROP_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_SIMPLE_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_CRON_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_BLOB_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_TRIGGERS;
-- DROP TABLE IF EXISTS QRTZ_JOB_DETAILS;
-- DROP TABLE IF EXISTS QRTZ_CALENDARS;

CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS
(
    SCHED_NAME TEXT NOT NULL,
    JOB_NAME TEXT NOT NULL,
    JOB_GROUP TEXT NOT NULL,
    DESCRIPTION TEXT NULL,
    JOB_CLASS_NAME TEXT NOT NULL,
    IS_DURABLE INTEGER NOT NULL,
    IS_NONCONCURRENT INTEGER NOT NULL,
    IS_UPDATE_DATA INTEGER NOT NULL,
    REQUESTS_RECOVERY INTEGER NOT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS
(
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    JOB_NAME TEXT NOT NULL,
    JOB_GROUP TEXT NOT NULL,
    DESCRIPTION TEXT NULL,
    NEXT_FIRE_TIME INTEGER NULL,
    PREV_FIRE_TIME INTEGER NULL,
    PRIORITY INTEGER NULL,
    TRIGGER_STATE TEXT NOT NULL,
    TRIGGER_TYPE TEXT NOT NULL,
    START_TIME INTEGER NOT NULL,
    END_TIME INTEGER NULL,
    CALENDAR_NAME TEXT NULL,
    MISFIRE_INSTR INTEGER NULL,
    MISFIRE_ORIG_FIRE_TIME INTEGER NULL,
    EXECUTION_GROUP TEXT NULL,
    JOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
        REFERENCES QRTZ_JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS
(
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    REPEAT_COUNT INTEGER NOT NULL,
    REPEAT_INTERVAL INTEGER NOT NULL,
    TIMES_TRIGGERED INTEGER NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS
(
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    STR_PROP_1 TEXT NULL,
    STR_PROP_2 TEXT NULL,
    STR_PROP_3 TEXT NULL,
    INT_PROP_1 INTEGER NULL,
    INT_PROP_2 INTEGER NULL,
    LONG_PROP_1 INTEGER NULL,
    LONG_PROP_2 INTEGER NULL,
    DEC_PROP_1 NUMERIC NULL,
    DEC_PROP_2 NUMERIC NULL,
    BOOL_PROP_1 INTEGER NULL,
    BOOL_PROP_2 INTEGER NULL,
    TIME_ZONE_ID TEXT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS
(
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    CRON_EXPRESSION TEXT NOT NULL,
    TIME_ZONE_ID TEXT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS
(
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    BLOB_DATA BLOB NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
    FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
        REFERENCES QRTZ_TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS
(
    SCHED_NAME TEXT NOT NULL,
    CALENDAR_NAME TEXT NOT NULL,
    CALENDAR BLOB NOT NULL,
    PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS
(
    SCHED_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS
(
    SCHED_NAME TEXT NOT NULL,
    ENTRY_ID TEXT NOT NULL,
    TRIGGER_NAME TEXT NOT NULL,
    TRIGGER_GROUP TEXT NOT NULL,
    INSTANCE_NAME TEXT NOT NULL,
    FIRED_TIME INTEGER NOT NULL,
    SCHED_TIME INTEGER NOT NULL,
    PRIORITY INTEGER NOT NULL,
    STATE TEXT NOT NULL,
    JOB_NAME TEXT NULL,
    JOB_GROUP TEXT NULL,
    IS_NONCONCURRENT INTEGER NULL,
    REQUESTS_RECOVERY INTEGER NULL,
    EXECUTION_GROUP TEXT NULL,
    PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE
(
    SCHED_NAME TEXT NOT NULL,
    INSTANCE_NAME TEXT NOT NULL,
    LAST_CHECKIN_TIME INTEGER NOT NULL,
    CHECKIN_INTERVAL INTEGER NOT NULL,
    PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

CREATE TABLE IF NOT EXISTS QRTZ_LOCKS
(
    SCHED_NAME TEXT NOT NULL,
    LOCK_NAME TEXT NOT NULL,
    PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);

-- SQLite 触发器（用于级联删除）
CREATE TRIGGER IF NOT EXISTS DELETE_SIMPLE_TRIGGER
AFTER DELETE ON QRTZ_TRIGGERS
BEGIN
    DELETE FROM QRTZ_SIMPLE_TRIGGERS
    WHERE SCHED_NAME = OLD.SCHED_NAME
      AND TRIGGER_NAME = OLD.TRIGGER_NAME
      AND TRIGGER_GROUP = OLD.TRIGGER_GROUP;
END;

CREATE TRIGGER IF NOT EXISTS DELETE_SIMPROP_TRIGGER
AFTER DELETE ON QRTZ_TRIGGERS
BEGIN
    DELETE FROM QRTZ_SIMPROP_TRIGGERS
    WHERE SCHED_NAME = OLD.SCHED_NAME
      AND TRIGGER_NAME = OLD.TRIGGER_NAME
      AND TRIGGER_GROUP = OLD.TRIGGER_GROUP;
END;

CREATE TRIGGER IF NOT EXISTS DELETE_CRON_TRIGGER
AFTER DELETE ON QRTZ_TRIGGERS
BEGIN
    DELETE FROM QRTZ_CRON_TRIGGERS
    WHERE SCHED_NAME = OLD.SCHED_NAME
      AND TRIGGER_NAME = OLD.TRIGGER_NAME
      AND TRIGGER_GROUP = OLD.TRIGGER_GROUP;
END;

CREATE TRIGGER IF NOT EXISTS DELETE_BLOB_TRIGGER
AFTER DELETE ON QRTZ_TRIGGERS
BEGIN
    DELETE FROM QRTZ_BLOB_TRIGGERS
    WHERE SCHED_NAME = OLD.SCHED_NAME
      AND TRIGGER_NAME = OLD.TRIGGER_NAME
      AND TRIGGER_GROUP = OLD.TRIGGER_GROUP;
END;
